site_name: HanzeWiki
theme:
  name: material
  custom_dir: overrides/
  palette:
  - scheme: default
    accent: indiego
    toggle:
      icon: material/weather-night
      name: Switch to dark mode
  - scheme: slate
    primary:
    accent: indiego
    toggle:
      icon: material/weather-sunny
      name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  language: en
  # logo: img/logo.png
  favicon: img/favicon.ico
  icon:
    logo: fontawesome/solid/life-ring
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - header.autohide
markdown_extensions:
  - toc:
      permalink: ⚓︎
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
extra:
  alternate:
    # Switch to English
    - name: English
      lang: en
    #Switch to Dutch
    - name: Dutch
      lang: nl
  # version:
  #   provider: mike
  social:
    - icon: fontawesome/brands/discord
      link: https://twitter.com/squidfunk
copyright: Copyright &copy; 2016 - 2020 Martin Donath
extra_css:
  - stylesheets/extra.css
plugins:
  - search
nav:
    - Home: 'index.md'
    - General:
        - 'General Information': 'general.md'
        - 'Links': 'general/links.md'
        - 'Departments':
            - 'Student Administration': 'general/departments/studentadministration.md'
            - 'International Office': 'general/departments/internationaloffice.md'
            - 'Study Desk': 'general/departments/studydesk.md'
            - 'International Student Team': 'general/departments/internationalstudentteam.md'
    - Locations:
        - 'Van Doorenveste (ZP11)': 'locations/zp11.md'
        - 'Van Olsttoren (ZP07)': 'locations/zp07.md'
        - 'Willem-Alexander Sports Centre (ZP17)': 'locations/zp17.md'
        - 'Digital Society (ZE10)': 'locations/ze10.md'
        - 'De Deimten (DD05)': 'locations/dd05.md'
    - Osiris:
        - 'General Information - Osiris': 'osiris/osiris-general.md'
    - Blackboard:
        - 'General Information - Blackboard': 'blackboard/bb-general.md'
    - About:
        - 'Who are we': 'about/who-are-we.md'
        - 'Changelog': 'about/changelog.md'
        - 'Privacy': 'about/privacy.md'
        - 'License': 'about/license.md'
