site_name: HanzeWiki
theme:
  name: material
  custom_dir: overrides/
  palette:
  - scheme: default
    accent: indiego
    toggle:
      icon: material/weather-night
      name: Switch to dark mode
  - scheme: slate
    primary:
    accent: indiego
    toggle:
      icon: material/weather-sunny
      name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  language: en
  # logo: img/logo.png
  favicon: img/favicon.ico
  icon:
    logo: fontawesome/solid/life-ring
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - header.autohide
markdown_extensions:
  - toc:
      permalink: ⚓︎
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
extra:
  # alternate:
  #   # Switch to English
  #   - name: English
  #     lang: en
  #     link: localhost:8000/en/
  #   #Switch to Dutch
  #   - name: Dutch
  #     lang: nl
  #     link: localhost:8000/nl/
  # version:
  #   provider: mike
  social:
    - icon: fontawesome/brands/discord
      link: https://twitter.com/squidfunk
copyright: Copyright &copy; 2016 - 2020 Martin Donath
extra_css:
  - stylesheets/extra.css
plugins:
  - search
nav:
    - Home: 'index.md'
    - General:
        - 'Welcome': 'general/general.md'
        - 'Outlook': 'general/outlook.md'
        - 'Digirooster': 'general/digirooster.md'
        - 'OnStage': 'general/onstage.md'
        - 'Departments':
            - 'Student Administration': 'general/departments/studentadministration.md'
            - 'International Office': 'general/departments/internationaloffice.md'
            - 'Study Desk': 'general/departments/studydesk.md'
            - 'International Student Team': 'general/departments/internationalstudentteam.md'
            - 'ICT Desk': 'general/departments/ictdesk.md'
            - 'Media Desk': 'general/departments/mediadesk.md'
            - 'CMD Front Office': 'general/departments/cmdfrontoffice.md'
            - 'Career Desk': 'general/departments/careerdesk.md'
            - 'Makerspace': 'general/departments/makerspace.md'
            - 'Spacelab': 'general/departments/spacelab.md'
    - Osiris:
        - 'General Information - Osiris': 'osiris/osiris-general.md'
        - 'Osiris Versions': 'osiris/osiris-version.md'
        - 'Old Osiris':
          - 'Personal Details': 'osiris/old/o-personal-details.md'
          - 'Enrollment Status': 'osiris/old/o-enrollmentstatus.md'
          - 'Progress View': 'osiris/old/o-progress-view.md'
          - 'Results': 'osiris/old/o-results.md'
          - 'Cases': 'osiris/old/o-cases.md'
          - Courses:
            - 'Courses Page': 'osiris/old/o-courses.md'
            - 'Course Register': 'osiris/old/o-course-register.md'
            - 'Course Deregister': 'osiris/old/o-course-de-register.md'
          - 'Stay Abroad': 'osiris/old/o-stay-abroad.md'
        - 'New Osiris':
            - 'Personal Details': 'osiris/new/n-personal-details.md'
            - 'Enrollment Status': 'osiris/new/n-enrollmentstatus.md'
            - 'Progress View': 'osiris/new/n-progress-view.md'
            - 'Results': 'osiris/new/n-results.md'
            - 'Cases': 'osiris/new/n-cases.md'
            - Courses:
              - 'Course Page': 'osiris/new/n-courses.md'
              - 'Course Register': 'osiris/new/n-course-register.md'
              - 'Course Deregister': 'osiris/new/n-course-de-register.md'
    - Blackboard:
        - 'General Information - Blackboard': 'blackboard/bb-general.md'
    - About:
        - 'Who are we': 'about/who-are-we.md'
        - 'Changelog': 'about/changelog.md'
        - 'Privacy': 'about/privacy.md'
        - 'License': 'about/license.md'
